### ISSUE TITLE
Help needed in following 'Development' installation instruction through 'Without Oracle Instant Client' on Windows.

### ISSUE THREAD

**Issue by AmitDigga** [latera/homs#478]
### Step 5

```
5. Add environment variable $HOMS_URL to .env file with URL to your HOMS:

📌 For access to host machine OS X users can use special DNS name host.docker.internal as host in tnsnames.ora (details).

    HOMS_URL=http://docker.for.mac.localhost:3000/api
```

1. What is HOMS_URL over here? 
2. It says specific instruction for mac, but what to do on windows?

### Step 6

```
6. Create your own configs from samples:

find config -name '*.sample' | xargs -I{} sh -c 'cp $1 ${1%.*}' -- {}
```

1. What can be windows equivalent over here?  I just copied all sample files and removed `sample` from their name.

### Step 8 

```
Add test environment to config/database.yml:

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['HOMS_DB_HOST'] %>
  port: <%= ENV['HOMS_DB_PORT'] %>
  database: <%= ENV['HOMS_DB_NAME'] %>
  username: <%= ENV['HOMS_DB_USER'] %>
  password: <%= ENV['HOMS_DB_PASSWORD'] %>
```

1. But test enviroment was already there in `config/database.yml`. Maybe because i already copied this file in step 6?
