### ISSUE TITLE
Minio URL is hard coded

### ISSUE THREAD

**Issue by JamiePhonic** [latera/homs#605]
It looks like the Minio URL is hard coded as `127.0.0.1:9090` in `homs/config/hbw.yml.sample`

This doesnt appear to work in docker based environments since 127.0.0.1 refers to the homs container, so the file upload in the `new customer` example will just hang and the logs show `Seahorse::Client::NetworkingError (Failed to open TCP connection to 127.0.0.1:9000 (Connection refused - connect(2) for "127.0.0.1" port 9000)):`

**Comment by TimAle** [comment]
Hi James! 
Thank you, that's true, will fix it in https://github.com/latera/homs/pull/606

**Comment by JamiePhonic** [comment]
Might also be worth mentioning that the Minio Web UI port is randomised each time it's started.

the Minio start command in docker-compose.yaml should be changed to `command: "server /opt/minio --console-address ':9001'"` to force start it on 9001 and a new port mapping added to the ENV file to handle it.

```yaml
minio:
    image: minio/minio
    container_name: minio
    command: "server /opt/minio --console-address ':9001'"
    restart: always
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
      TZ: $TIMEZONE
    volumes:
      - ./data/minio:/opt/minio
    ports:
      - $MINIO_PORT:9000
      - $MINIO_UI_PORT:9001
```

I also made TimeZone an ENV variable to make it easier to change it for all containers at once.
